version: '3.8'

services:

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my_blog_php
        volumes:
            - ./:/var/www/html
        networks:
            - blog_network
        depends_on:
            - mysql


    nginx:
        image: nginx:alpine
        container_name: blog_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - blog_network
        depends_on:
            - php

    mysql:
        image: mysql:8.0
        container_name: my_blog_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog_db
            MYSQL_USER: blog_user
            MYSQL_PASSWORD: blog_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - blog_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my_blog_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: blog_user
            PMA_PASSWORD: blog_pass
        ports:
            - "8081:80"
        networks:
            - blog_network
        depends_on:
            - mysql

networks:
    blog_network:
        driver: bridge

volumes:
    mysql_data:
